const cards = document.querySelector(".cards");
document.querySelector(".plus").addEventListener("click",Handeled);
function Handeled(){
    const card = document.createElement("div");
    card.classList = "card";
    const cardas = document.createElement("div");
    cardas.classList = "cardas";
    card.appendChild(cardas);
    const text = document.createElement("div");
    text.classList = "text";
    cardas.appendChild(text);
    const p = document.createElement("p");
    p.innerText = "day";
    text.appendChild(p);
    const div = document.createElement("div");
    const i = document.createElement("i");
    i.classList = "fas fa-sun";
    div.appendChild(i);
    text.appendChild(div);
    const h2 = document.createElement("h2");
    h2.innerText = "07:00";
    text.appendChild(h2);
    const togle = document.createElement("div");
    togle.classList = "togle";
    const circle = document.createElement("div");
    circle.classList = "circle";
    circle.innerText = "ON";
    togle.appendChild(circle);
    card.appendChild(togle);
    cards.appendChild(card);
}
